repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
-   repo: https://github.com/psf/black
    rev: '22.6.0'
    hooks:
    -   id: black
-   repo: https://github.com/pre-commit/mirrors-pylint
    rev: v3.0.0a5
    hooks:
    -   id: pylint
